### ISSUE TITLE
Do you plan on updating to Android 10 source?

### ISSUE THREAD

**Issue by Neves4** [PixelExperience-Devices/device_xiaomi_whyred#3]
Hi guys!

Since I unlocked my bootloader, 3 months ago, I'm using pixel experience and loving it. It's really what I was expecting and performance/battery are great.

**Q:** Do you plan on updating the sources to Android 10? Is it dependent on Lineage?

Thanks!

**Comment by mateushonorato** [comment]
I believe they do, some commits in the pie build suggest that by making it easier to do the work. You just have to be patient, this should take some time since the source code of android 10 was just released some days ago. Also, I believe this is not the right place to make this question, it should be reserved to bug reports I guess.

**Comment by Neves4** [comment]
Hey @mateushonorato !

Thanks for the answer!

Just wanted to understand the devs willingness to continue development, as our phone is no longer maintained officially by LineageOS... Also saw some commits, I hope that's an yes :)

I apologize if that's not the correct place... I'll leave the issue opened one more day and close if no answer.
